I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 90, in script
    o "Что делать?"
Exception: Sayer 'o' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 90, in script
    o "Что делать?"
  File "C:\Users\pupil\Desktop\MLWFE\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\pupil\Desktop\MLWFE\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\pupil\Desktop\MLWFE\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'o' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
Возможно любовь всё исправит? 1.0
Tue Apr 30 14:32:40 2024
